# Generated by Django 4.1.1 on 2022-09-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(verbose_name=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
