# Generated by Django 4.0.5 on 2022-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('email_id', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
